<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="v-hj-022d" name="com.advantage.tests.testLink.CreateTestSuiteFlow" tests="1" failures="1" timestamp="3 Apr 2014 05:11:45 GMT" time="124.804" errors="0">
  <testcase name="runCreateTestSuiteFlow" time="124.804" classname="com.advantage.tests.testLink.CreateTestSuiteFlow">
    <failure type="com.advantage.genericexceptions.ClickNoSuchElementException" message="Could not find &#039;//*[@id=&#039;extdd-1&#039;]/a&#039; due to exception:  java.lang.NullPointerException:  null">
      <![CDATA[com.advantage.genericexceptions.ClickNoSuchElementException: Could not find '//*[@id='extdd-1']/a' due to exception:  java.lang.NullPointerException:  null
	at com.advantage.framework.Framework.click(Unknown Source)
	at com.advantage.framework.Framework.click(Unknown Source)
	at com.advantage.pages.testLink.TestSpecification.clickProjFolder(Unknown Source)
	at com.advantage.tests.testLink.CreateTestSuiteFlow.runCreateTestSuiteFlow(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.run(TestNG.java:1036)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- runCreateTestSuiteFlow -->
</testsuite> <!-- com.advantage.tests.testLink.CreateTestSuiteFlow -->
