<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="v-hj-022d" name="com.advantage.tests.LoginTest1" tests="3" failures="2" timestamp="7 Mar 2014 08:25:02 GMT" time="87.935" errors="0">
  <testcase name="runLoginPositiveFlow" time="41.420" classname="com.advantage.tests.LoginTest1">
    <failure type="com.advantage.genericexceptions.WrongPageException" message="Not at Login page (must contain &#039;/Login.html&#039;)  URL:  http://ppud9050:8080/upm/error/LoginFailed.html?cppt=9
">
      <![CDATA[com.advantage.genericexceptions.WrongPageException: Not at Login page (must contain '/Login.html')  URL:  http://ppud9050:8080/upm/error/LoginFailed.html?cppt=9

	at com.advantage.framework.Framework.initialize(Framework.java:139)
	at com.advantage.pages.Login.<init>(Login.java:45)
	at com.advantage.pages.Navigation.clickLogout(Navigation.java:67)
	at com.advantage.tests.LoginTest1.runLoginPositiveFlow(LoginTest1.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$0(SuiteRunner.java:333)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- runLoginPositiveFlow -->
  <testcase name="runPasswordBlankFlow" time="7.727" classname="com.advantage.tests.LoginTest1"/>
  <testcase name="runLoginPositiveFlow" time="38.788" classname="com.advantage.tests.LoginTest1">
    <failure type="com.advantage.genericexceptions.WrongPageException" message="Not at Login page (must contain &#039;/Login.html&#039;)  URL:  http://ppud9050:8080/upm/error/LoginFailed.html?cppt=7
">
      <![CDATA[com.advantage.genericexceptions.WrongPageException: Not at Login page (must contain '/Login.html')  URL:  http://ppud9050:8080/upm/error/LoginFailed.html?cppt=7

	at com.advantage.framework.Framework.initialize(Framework.java:139)
	at com.advantage.pages.Login.<init>(Login.java:45)
	at com.advantage.pages.Navigation.clickLogout(Navigation.java:67)
	at com.advantage.tests.LoginTest1.runLoginPositiveFlow(LoginTest1.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.access$0(SuiteRunner.java:333)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:368)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- runLoginPositiveFlow -->
</testsuite> <!-- com.advantage.tests.LoginTest1 -->
